name: "Fork Sync"
on:
  schedule:
    - cron:  '0 */2 * * *'
  workflow_dispatch:
jobs:
  sync-master:
    runs-on: ubuntu-latest
    name: "Sync develop branch from karatelabs repo"
    steps:
    - name: "Checkout: develop"
      uses: actions/checkout@v2
      with:
        ref: develop
    - name: "Update: develop"
      id: sync-develop
      uses: aormsby/Fork-Sync-With-Upstream-action@main 
      with:
        upstream_sync_repo: karatelabs/karate
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: develop
        target_sync_branch: develop
        upstream_pull_args: --ff-only
        test_mode: True
    - name: Timestamp
      run: date
