name: launchable-collect

on:
  schedule:
    - cron:  '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v3
      with:
        ref: develop
        fetch-depth: 2
    - name: upstream fetch check
      id: upstreamfc
      run: |
        SHA=$(git rev-parse HEAD~)
        if [[ "$(cat current_sha.txt)" != "$SHA" ]] 
        then 
          echo $(cat current_sha.txt) " different than " $SHA
          echo '::set-output name=upstream_changes::1'
        else 
          echo $(cat current_sha.txt) " same as " $SHA
          echo '::set-output name=upstream_changes::0'
        fi
    - name: cancel if no changes
      uses: andymckay/cancel-action@0.2
      if: steps.upstreamfc.outputs.upstream_changes == 0
    - name: Should run tests?
      run: test "${{ steps.upstreamfc.outputs.upstream_changes }}" = 1
    - uses: actions/setup-python@v2
    - name: set up jdk 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11
    - name: cache maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Setup test result collector
      run: |
        pip install pandas urllib3 lxml
        git clone ${{ secrets.COLLECT_REPO }}
    - name: Launchable tests record
      env:
        LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}
      run: |
        pip3 install --user launchable~=1.0 > /dev/null
        export PATH=~/.local/bin:$PATH
        set -x
        launchable verify
        launchable record build --name $GITHUB_RUN_ID-$GITHUB_SHA --source src=.
    - name: build with maven
      run: mvn -B clean test -Dmaven.test.failure.ignore=true
    - name: run test result collector
      run: |
        cd test-result-collector
        python collect_test_results.py --api-host ${{ secrets.API_HOST }} --api-key ${{ secrets.API_KEY }} --prj-name karate --build-id $GITHUB_RUN_ID-$GITHUB_SHA --repo-folder ../
    - name: Send test results to launchable
      env:
        LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}
      run: |
        launchable record tests --build $GITHUB_RUN_ID-$GITHUB_SHA maven ./karate-junit4/target/surefire-reports ./karate-robot/target/surefire-reports ./karate-core/target/surefire-reports ./karate-junit5/target/surefire-reports ./karate-mock-servlet/target/surefire-reports ./karate-demo/target/surefire-reports
    - name: update sha file
      run: echo $(git rev-parse --verify HEAD) > current_sha.txt
    - name: stage commit sha
      run: |
        git add current_sha.txt
    - name: Commit & Push updated sha file
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: "update commit sha file"
        branch: "develop"
